'use client'

import React, { createContext, useContext, useState, useEffect } from 'react'

type Language = 'en' | 'hi' | 'mr'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

// Base English keys – all other languages must include these keys
const en: Record<string, string> = {
  dashboard: 'Dashboard',
  predict: 'Predict Disease',
  analytics: 'Analytics',
  reports: 'Reports',
  farmers_guide: "Farmer's Guide",
  weather: 'Weather',
  login: 'Login',
  register: 'Register',
  logout: 'Logout',
  upload_image: 'Upload Image',
  disease_detected: 'Disease Detected',
  confidence: 'Confidence',
  treatment: 'Treatment',
  prevention: 'Prevention',
  // Dashboard
  my_dashboard: 'My Dashboard',
  new_prediction: 'New Prediction',
  predict_disease: 'Predict Disease',
  view_analytics: 'View Analytics',
  upload_crop_image: 'Upload crop image',
  track_trends: 'Track trends',
  weather_alert: 'Weather Alert',
  check_conditions: 'Check conditions',
  prevention_tips: 'Prevention Tips',
  stay_protected: 'Stay protected',
  weather_disease_risk: 'Weather & disease risk',
  enter_region: 'Enter region (e.g. Mumbai)',
  get_weather: 'Get weather',
  checking: 'Checking...',
  full_weather_page: 'Full weather page',
  total_predictions: 'Total Predictions',
  avg_confidence: 'Avg Confidence',
  unique_diseases: 'Unique Diseases',
  prediction_history: 'Prediction History',
  date: 'Date',
  disease: 'Disease',
  crop_type: 'Crop Type',
  no_predictions_yet: 'No predictions yet. Start by uploading an image!',
  risk: 'Risk',
  // Predict
  crop_disease_detection: 'Crop Disease Detection',
  upload_image_title: 'Upload Image',
  drag_drop_or_click: 'Drag & drop an image, or click to select',
  drop_here: 'Drop the image here',
  crop_type_label: 'Crop Type',
  region_label: 'Region',
  soil_type_label: 'Soil Type',
  select_crop_type: 'Select crop type',
  select_soil_type: 'Select soil type',
  enter_region_placeholder: 'Enter your region',
  capture: 'Capture',
  cancel: 'Cancel',
  take_photo: 'Take Photo',
  analyze: 'Analyze',
  reset: 'Reset',
  please_select_image: 'Please select an image',
  prediction_completed: 'Prediction completed!',
  prediction_failed: 'Prediction failed',
  camera_denied: 'Camera access denied. Please allow camera permissions.',
  invalid_image_title: 'Invalid image',
  ok_upload_again: 'OK, upload again',
  recommended_medicine: 'Recommended medicine & treatment',
  fertilizer_suggestion: 'Fertilizer suggestion',
  // Login / Register
  email: 'Email',
  password: 'Password',
  logging_in: 'Logging in...',
  no_account_register: "Don't have an account?",
  full_name: 'Full Name',
  region_optional: 'Region (Optional)',
  registering: 'Registering...',
  have_account_login: 'Already have an account?',
  login_success: 'Login successful!',
  login_failed: 'Login failed',
  register_success: 'Registration successful!',
  register_failed: 'Registration failed',
  // Analytics
  crop_filter: 'Crop filter',
  disease_frequency: 'Disease Frequency',
  crop_health: 'Crop Health',
  monthly_trends: 'Monthly Trends',
  region_wise: 'Region-wise',
  export_pdf: 'Export PDF',
  export_csv: 'Export CSV',
  disease_map: 'Disease Map',
  filter_by_crop: 'Filter by crop',
  all_crops: 'All crops',
  not_specified: 'Not specified',
  // Reports
  crop_disease_report: 'Crop Disease Detection Report',
  period: 'Period',
  summary: 'Summary',
  total_predictions_report: 'Total Predictions',
  generate_report: 'Generate Report',
  export_report: 'Export Report',
  // Farmers guide
  farmers_guide_title: "Farmer's Guide",
  crop_care_tips: 'Crop Care Tips',
  seasonal_tasks: 'Seasonal Tasks',
  spring: 'Spring',
  summer: 'Summer',
  fall: 'Fall',
  winter: 'Winter',
  // Weather
  weather_disease_risk_title: 'Weather & Disease Risk',
  enter_region_weather: 'Enter your region (e.g., New York)',
  check_weather: 'Check Weather',
  weather_conditions: 'Weather Conditions',
  temperature: 'Temperature',
  humidity: 'Humidity',
  recommendation: 'Recommendation',
  high: 'high',
  moderate: 'moderate',
  low: 'low',
  please_enter_region: 'Please enter a region (e.g. city or country)',
  could_not_fetch_weather: 'Could not fetch weather. Try another region.',
  welcome_back: 'Welcome back',
  farm_overview: "Here's your farm overview",
  more: 'More',
  about: 'About',
  contact: 'Contact',
  help: 'Help',
  privacy: 'Privacy',
  ai_disease_analysis: 'AI Disease Analysis',
  upload_subtitle: 'Upload a clear leaf photo for instant AI diagnosis with treatment recommendations.',
  image_ready: 'Image ready — click Analyse',
  image_format_hint: 'JPG, JPEG, PNG · Max 10MB',
  other_custom: 'Other (Custom)',
  crop_placeholder: 'e.g. Mango, Banana…',
  analysis_results: 'Analysis Results',
  analysis_failed: 'Analysis Failed',
  try_again: 'Try again',
  suggested_diagnosis: 'Suggested Diagnosis · AI Estimate',
  ai_confidence: 'AI Confidence',
  low_confidence_warning: 'Low confidence — image quality or lighting may be affecting accuracy.',
  est_crop_health: 'Est. Crop Health',
  est_severity: 'Estimated Severity',
  expert_review_recommended: 'Expert Review Recommended.',
  expert_review_details: 'These are AI-suggested results based on visual patterns. For confirmation, consult a local agricultural extension officer or agronomist before applying any treatment.',
  top_3_diseases: 'Top 3 Possible Diseases',
  top_3_desc: "The model's probability estimates — any of these could be the actual condition.",
  likely: 'likely',
  disease_analysis: 'Disease Analysis',
  pathogen: 'Pathogen',
  symptoms: 'Symptoms',
  suggested_treatment: 'Suggested Treatment (Verify with Expert)',
  treatment_warning: 'Always confirm dosage and pesticide suitability with a local agronomist before application.',
  soil_advice: 'Soil & Field Advice',
  analyze_another: '↺ Analyse Another Image',
  no_results_yet: 'No results yet',
  upload_instruction: 'Upload a leaf image and click Analyse Disease to get started.',
  no_crop_health_data: 'No crop health data available. Make predictions with crop type information to see statistics.',
  no_monthly_trend_data: 'No monthly trend data available. Make predictions to see trends over time.',
  no_region_data: 'No region data available. Make predictions with region information to see the chart.',
  loading_reports: 'Loading reports…',
  analytics_history: 'Analytics & History',
  recent_predictions: 'Recent disease predictions',
  actions: 'Actions',
  prediction_details: 'Prediction Details',
  loading_details: 'Loading details…',
  live_weather_disease_risk: 'Live Weather · Disease Risk',
  real_time_weather_info: 'Real-time data from Open-Meteo — works for any city worldwide.',
  works_for_any_city: 'Works for any city or district',
  enter_region_placeholder_2: 'e.g. Pune, Mumbai, Delhi, Bangalore…',
  loading: 'Loading…',
  based_on_current_conditions: 'Based on current conditions',
  risk_factors_detected: 'Risk Factors Detected',
  weather_disclaimer: 'Risk is modelled from live weather conditions. Always combine with field scouting — consult a local agronomist before treatment decisions.',
  precipitation: 'Precipitation',
  cloud_cover: 'Cloud Cover',
  dew_point: 'Dew Point',
  wind_speed: 'Wind Speed',
  high_disease_risk: 'High Disease Risk',
  moderate_disease_risk: 'Moderate Disease Risk',
  low_disease_risk: 'Low Disease Risk',
  high_risk_advice: 'High disease risk. Avoid overhead irrigation, improve air circulation, and consider preventive fungicide application. Inspect crops daily for early symptoms.',
  moderate_risk_advice: 'Moderate disease risk. Monitor crops closely, ensure proper ventilation, and avoid excess moisture on leaves. Scout for disease signs every 2-3 days.',
  low_risk_advice: 'Low disease risk. Maintain good agronomic practices. Conditions are currently unfavourable for most crop pathogens.',
  please_enter_region_or_city: 'Please enter a region or city name',
  finding_location: 'Finding location…',
  loading_live_weather: 'Loading live weather data…',
  knowledge_hub: 'Knowledge Hub',
  farmers_guide_subtitle: 'Expert tips, seasonal guides, and best practices for healthy crops.',
  quick_reference: 'Quick Reference',
  tomato: 'Tomato',
  potato: 'Potato',
  corn: 'Corn',
  tomato_tip_1: 'Water at the base, avoid wetting leaves',
  tomato_tip_2: 'Provide 6-8 hours of sunlight daily',
  tomato_tip_3: 'Use stakes or cages for support',
  tomato_tip_4: 'Fertilize every 2-3 weeks',
  tomato_tip_5: 'Check for pests regularly',
  potato_tip_1: 'Plant in well-drained soil',
  potato_tip_2: 'Keep soil consistently moist',
  potato_tip_3: 'Hill soil around plants as they grow',
  potato_tip_4: 'Harvest when leaves turn yellow',
  potato_tip_5: 'Store in cool, dark place',
  corn_tip_1: 'Plant in blocks for better pollination',
  corn_tip_2: 'Water deeply once a week',
  corn_tip_3: 'Fertilize with nitrogen-rich fertilizer',
  corn_tip_4: 'Harvest when kernels are milky',
  corn_tip_5: 'Plant in full sun',
  spring_task_1: 'Prepare soil',
  spring_task_2: 'Start seedlings',
  spring_task_3: 'Apply compost',
  spring_task_4: 'Check irrigation',
  summer_task_1: 'Water regularly',
  summer_task_2: 'Mulch around plants',
  summer_task_3: 'Monitor pests',
  summer_task_4: 'Harvest early crops',
  fall_task_1: 'Harvest remaining crops',
  fall_task_2: 'Prepare for winter',
  fall_task_3: 'Plant cover crops',
  fall_task_4: 'Clean tools',
  winter_task_1: 'Plan next season',
  winter_task_2: 'Maintain equipment',
  winter_task_3: 'Order seeds',
  winter_task_4: 'Review past season',
  watering_guide: 'Watering Guide',
  watering_desc: 'Water early morning or evening. Most crops need 1-2 inches per week. Check soil moisture before watering.',
  sunlight_req: 'Sunlight Requirements',
  sunlight_desc: 'Most vegetables need 6-8 hours of direct sunlight. Leafy greens can tolerate partial shade.',
  disease_prev: 'Disease Prevention',
  disease_desc: 'Rotate crops annually, use disease-resistant varieties, maintain proper spacing, and remove infected plants immediately.',
  our_story: 'Our Story',
  about_cropguard: 'About CropGuard',
  about_cropguard_desc: 'AI-powered crop disease detection built by farmers, for farmers — making precision agriculture accessible to everyone.',
  get_in_touch: 'Get in Touch',
  contact_desc: 'Have questions about CropGuard? Need support or want to provide feedback? We\'d love to hear from you.',
  we_respond_24_hours: 'We respond within 24 hours',
  our_contributors: 'Our Contributors',
  meet_the_creators: 'Meet the creators behind Crop Disease Analysis',
  support_center: 'Support Center',
  help_faq: 'Help & FAQ',
  help_desc: 'Everything you need to know to get the most out of CropGuard\'s AI-powered features.',
  privacy_policy: 'Privacy Policy',
  privacy_desc: 'We are committed to protecting your privacy and the security of your data.',
}

const hi: Record<string, string> = {
  ...en,
  dashboard: 'डैशबोर्ड', predict: 'रोग की भविष्यवाणी', analytics: 'विश्लेषण', reports: 'रिपोर्ट',
  farmers_guide: 'किसान गाइड', weather: 'मौसम', login: 'लॉगिन', register: 'रजिस्टर', logout: 'लॉगआउट',
  upload_image: 'छवि अपलोड करें', disease_detected: 'रोग का पता चला', confidence: 'आत्मविश्वास', treatment: 'उपचार', prevention: 'रोकथाम',
  my_dashboard: 'मेरा डैशबोर्ड', new_prediction: 'नई भविष्यवाणी', predict_disease: 'रोग की भविष्यवाणी', view_analytics: 'विश्लेषण देखें',
  upload_crop_image: 'फसल की छवि अपलोड करें', track_trends: 'ट्रेंड ट्रैक करें', weather_alert: 'मौसम अलर्ट', check_conditions: 'स्थिति जांचें',
  prevention_tips: 'रोकथाम टिप्स', stay_protected: 'सुरक्षित रहें', weather_disease_risk: 'मौसम और रोग जोखिम',
  enter_region: 'क्षेत्र दर्ज करें (जैसे मुंबई)', get_weather: 'मौसम लें', checking: 'जांच रहा है...', full_weather_page: 'पूर्ण मौसम पृष्ठ',
  total_predictions: 'कुल भविष्यवाणियां', avg_confidence: 'औसत आत्मविश्वास', unique_diseases: 'अद्वितीय रोग',
  prediction_history: 'भविष्यवाणी इतिहास', date: 'तारीख', disease: 'रोग', crop_type: 'फसल प्रकार',
  no_predictions_yet: 'अभी कोई भविष्यवाणी नहीं। एक छवि अपलोड करें!', risk: 'जोखिम',
  crop_disease_detection: 'फसल रोग पहचान', upload_image_title: 'छवि अपलोड करें',
  drag_drop_or_click: 'छवि खींचें या चुनने के लिए क्लिक करें', drop_here: 'यहां छोड़ें',
  crop_type_label: 'फसल प्रकार', region_label: 'क्षेत्र', soil_type_label: 'मिट्टी प्रकार',
  select_crop_type: 'फसल प्रकार चुनें', select_soil_type: 'मिट्टी प्रकार चुनें', enter_region_placeholder: 'अपना क्षेत्र दर्ज करें',
  capture: 'कैप्चर', cancel: 'रद्द करें', take_photo: 'फोटो लें', analyze: 'विश्लेषण', reset: 'रीसेट',
  please_select_image: 'कृपया एक छवि चुनें', prediction_completed: 'भविष्यवाणी पूर्ण!', prediction_failed: 'भविष्यवाणी विफल',
  camera_denied: 'कैमरा अनुमति दें।',
  email: 'ईमेल', password: 'पासवर्ड', logging_in: 'लॉग इन हो रहा है...', no_account_register: 'खाता नहीं है?',
  full_name: 'पूरा नाम', region_optional: 'क्षेत्र (वैकल्पिक)', registering: 'पंजीकरण हो रहा है...', have_account_login: 'पहले से खाता है?',
  login_success: 'लॉगिन सफल!', login_failed: 'लॉगिन विफल', register_success: 'पंजीकरण सफल!', register_failed: 'पंजीकरण विफल',
  crop_filter: 'फसल फ़िल्टर', disease_frequency: 'रोग आवृत्ति', crop_health: 'फसल स्वास्थ्य',
  monthly_trends: 'मासिक ट्रेंड', region_wise: 'क्षेत्रानुसार', export_pdf: 'PDF निर्यात', export_csv: 'CSV निर्यात',
  disease_map: 'रोग मानचित्र', filter_by_crop: 'फसल से फ़िल्टर', all_crops: 'सभी', not_specified: 'निर्दिष्ट नहीं',
  crop_disease_report: 'फसल रोग रिपोर्ट', period: 'अवधि', summary: 'सारांश',
  total_predictions_report: 'कुल भविष्यवाणियां', generate_report: 'रिपोर्ट बनाएं', export_report: 'रिपोर्ट निर्यात',
  farmers_guide_title: 'किसान गाइड', crop_care_tips: 'फसल देखभाल टिप्स', seasonal_tasks: 'मौसमी कार्य',
  spring: 'वसंत', summer: 'गर्मी', fall: 'पतझड़', winter: 'सर्दी',
  weather_disease_risk_title: 'मौसम और रोग जोखिम', enter_region_weather: 'अपना क्षेत्र दर्ज करें',
  check_weather: 'मौसम जांचें', weather_conditions: 'मौसम स्थितियां', temperature: 'तापमान', humidity: 'नमी',
  recommendation: 'सिफारिश', high: 'उच्च', moderate: 'मध्यम', low: 'कम',
  please_enter_region: 'कृपया क्षेत्र दर्ज करें', could_not_fetch_weather: 'मौसम प्राप्त नहीं हुआ।',
  welcome_back: 'वापसी पर स्वागत है',
  farm_overview: 'यहाँ आपके खेत का अवलोकन है',
  more: 'अधिक',
  about: 'के बारे में',
  contact: 'संपर्क करें',
  help: 'मदद',
  privacy: 'गोपनीयता',
  ai_disease_analysis: 'AI रोग विश्लेषण',
  upload_subtitle: 'तुरंत AI निदान और उपचार सुझावों के लिए पत्ती की साफ फोटो अपलोड करें।',
  image_ready: 'छवि तैयार है — विश्लेषण पर क्लिक करें',
  image_format_hint: 'JPG, JPEG, PNG · अधिकतम 10MB',
  other_custom: 'अन्य (कस्टम)',
  crop_placeholder: 'जैसे आम, केला…',
  analysis_results: 'विश्लेषण परिणाम',
  analysis_failed: 'विश्लेषण विफल',
  try_again: 'पुनः प्रयास करें',
  suggested_diagnosis: 'सुझाया गया निदान · AI अनुमान',
  ai_confidence: 'AI आत्मविश्वास',
  low_confidence_warning: 'कम आत्मविश्वास — छवि की गुणवत्ता या रोशनी सटीकता को प्रभावित कर सकती है।',
  est_crop_health: 'अनुमानित फसल स्वास्थ्य',
  est_severity: 'अनुमानित गंभीरता',
  expert_review_recommended: 'विशेषज्ञ समीक्षा अनुशंसित।',
  expert_review_details: 'ये दृश्य पैटर्न के आधार पर AI-सुझाए गए परिणाम हैं। पुष्टि के लिए, कोई भी उपचार लागू करने से पहले स्थानीय कृषि विस्तार अधिकारी या कृषिविज्ञानी से परामर्श लें।',
  top_3_diseases: 'शीर्ष 3 संभावित बीमारियां',
  top_3_desc: 'मॉडल की संभावना के अनुमान — इनमें से कोई भी वास्तविक स्थिति हो सकती है।',
  likely: 'संभावना',
  disease_analysis: 'रोग विश्लेषण',
  pathogen: 'रोगज़नक़',
  symptoms: 'लक्षण',
  suggested_treatment: 'सुझाया गया उपचार (विशेषज्ञ से पुष्टि करें)',
  treatment_warning: 'आवेदन से पहले हमेशा स्थानीय कृषिविज्ञानी के साथ खुराक और कीटनाशक उपयुक्तता की पुष्टि करें।',
  soil_advice: 'मिट्टी और खेत की सलाह',
  analyze_another: '↺ दूसरी छवि का विश्लेषण करें',
  no_results_yet: 'अभी तक कोई परिणाम नहीं',
  upload_instruction: 'शुरू करने के लिए एक पत्ती की छवि अपलोड करें और रोग का विश्लेषण करें पर क्लिक करें।',
  no_crop_health_data: 'फसल स्वास्थ्य का कोई डेटा उपलब्ध नहीं है। आँकड़े देखने के लिए फसल के प्रकार की जानकारी के साथ भविष्यवाणियां करें।',
  no_monthly_trend_data: 'कोई मासिक रुझान डेटा उपलब्ध नहीं है। समय के साथ रुझान देखने के लिए भविष्यवाणियां करें।',
  no_region_data: 'कोई क्षेत्रीय डेटा उपलब्ध नहीं है। चार्ट देखने के लिए क्षेत्र की जानकारी के साथ भविष्यवाणियां करें।',
  loading_reports: 'रिपोर्ट लोड हो रही हैं…',
  analytics_history: 'एनालिटिक्स और इतिहास',
  recent_predictions: 'हाल की बीमारी की भविष्यवाणियां',
  actions: 'क्रियाएं',
  prediction_details: 'भविष्यवाणी विवरण',
  loading_details: 'विवरण लोड हो रहा है…',
  live_weather_disease_risk: 'लाइव मौसम · रोग जोखिम',
  real_time_weather_info: 'Open-Meteo से रीयल-टाइम डेटा — दुनिया भर के किसी भी शहर के लिए काम करता है।',
  works_for_any_city: 'किसी भी शहर या जिले के लिए काम करता है',
  enter_region_placeholder_2: 'जैसे पुणे, मुंबई, दिल्ली, बैंगलोर…',
  loading: 'लोड हो रहा है…',
  based_on_current_conditions: 'वर्तमान स्थितियों के आधार पर',
  risk_factors_detected: 'जोखिम कारकों का पता चला',
  weather_disclaimer: 'जोखिम लाइव मौसम की स्थिति के आधार पर बताया गया है। हमेशा खेत की जांच के साथ इसे मिलाएं — उपचार निर्णय लेने से पहले स्थानीय कृषिविज्ञानी से परामर्श लें।',
  precipitation: 'वर्षण',
  cloud_cover: 'बादल छाना',
  dew_point: 'ओस बिंदु',
  wind_speed: 'हवा की गति',
  high_disease_risk: 'उच्च रोग जोखिम',
  moderate_disease_risk: 'मध्यम रोग जोखिम',
  low_disease_risk: 'कम रोग जोखिम',
  high_risk_advice: 'उच्च रोग जोखिम। ओवरहेड सिंचाई से बचें, हवा का संचार सुधारें और निवारक कवकनाशी लगाने पर विचार करें। जल्द लक्षणों के लिए फसलों का रोजाना निरीक्षण करें।',
  moderate_risk_advice: 'मध्यम रोग जोखिम। फसलों की बारीकी से निगरानी करें, उचित वेंटिलेशन सुनिश्चित करें और पत्तियों पर अतिरिक्त नमी से बचें। हर 2-3 दिनों में रोग के लक्षणों की जांच करें।',
  low_risk_advice: 'कम रोग जोखिम। अच्छी कृषि पद्धतियां जारी रखें। वर्तमान में अधिकांश फसल रोगजनकों के लिए स्थितियां प्रतिकूल हैं।',
  please_enter_region_or_city: 'कृपया किसी क्षेत्र या शहर का नाम दर्ज करें',
  finding_location: 'स्थान खोजा जा रहा है…',
  loading_live_weather: 'लाइव मौसम डेटा लोड हो रहा है…',
  knowledge_hub: 'ज्ञान केंद्र',
  farmers_guide_subtitle: 'स्वस्थ फसलों के लिए विशेषज्ञ युक्तियाँ, मौसमी गाइड और सर्वोत्तम प्रथाएँ।',
  quick_reference: 'त्वरित संदर्भ',
  tomato: 'टमाटर',
  potato: 'आलू',
  corn: 'मक्का',
  tomato_tip_1: 'जड़ों में पानी दें, पत्तियों को गीला करने से बचें',
  tomato_tip_2: 'प्रतिदिन 6-8 घंटे धूप दें',
  tomato_tip_3: 'सहारे के लिए स्टेक्स या पिंजरों का उपयोग करें',
  tomato_tip_4: 'हर 2-3 सप्ताह में खाद डालें',
  tomato_tip_5: 'नियमित रूप से कीटों की जांच करें',
  potato_tip_1: 'अच्छी जल निकासी वाली मिट्टी में लगाएं',
  potato_tip_2: 'मिट्टी को लगातार नम रखें',
  potato_tip_3: 'जैसे-जैसे पौधे बढ़ते हैं उनके चारों ओर मिट्टी चढ़ाएं',
  potato_tip_4: 'पत्तियां पीली पड़ने पर कटाई करें',
  potato_tip_5: 'ठंडी, अंधेरी जगह पर स्टोर करें',
  corn_tip_1: 'बेहतर परागण के लिए ब्लॉक में लगाएं',
  corn_tip_2: 'सप्ताह में एक बार गहराई से पानी दें',
  corn_tip_3: 'नाइट्रोजन युक्त उर्वरक डालें',
  corn_tip_4: 'जब दाने दूधिया हों तो कटाई करें',
  corn_tip_5: 'पूरी धूप में लगाएं',
  spring_task_1: 'मिट्टी तैयार करें',
  spring_task_2: 'पौध लगाना शुरू करें',
  spring_task_3: 'खाद डालें',
  spring_task_4: 'सिंचाई की जांच करें',
  summer_task_1: 'नियमित रूप से पानी दें',
  summer_task_2: 'पौधों के चारों ओर मल्च डालें',
  summer_task_3: 'कीटों की निगरानी करें',
  summer_task_4: 'शुरुआती फसलों की कटाई करें',
  fall_task_1: 'शेष फसलों की कटाई करें',
  fall_task_2: 'सर्दियों की तैयारी करें',
  fall_task_3: 'कवर फसलें लगाएं',
  fall_task_4: 'औजार साफ करें',
  winter_task_1: 'अगले मौसम की योजना बनाएं',
  winter_task_2: 'उपकरणों का रखरखाव करें',
  winter_task_3: 'बीज ऑर्डर करें',
  winter_task_4: 'पिछले मौसम की समीक्षा करें',
  watering_guide: 'सिंचाई गाइड',
  watering_desc: 'सुबह या शाम जल्दी पानी दें। अधिकांश फसलों को प्रति सप्ताह 1-2 इंच पानी की आवश्यकता होती है। पानी देने से पहले मिट्टी की नमी जांचें।',
  sunlight_req: 'धूप की आवश्यकताएं',
  sunlight_desc: 'आमतौर पर सब्जियों को 6-8 घंटे की सीधी धूप की आवश्यकता होती है। पत्तेदार सब्जियां आंशिक छाया सहन कर सकती हैं।',
  disease_prev: 'रोग निवारण',
  disease_desc: 'प्रतिवर्ष फसल चक्र अपनाएं, रोग-प्रतिरोधी किस्मों का उपयोग करें, उचित दूरी बनाए रखें और संक्रमित पौधों को तुरंत हटा दें।',
  our_story: 'हमारी कहानी',
  about_cropguard: 'क्रॉपगार्ड के बारे में',
  about_cropguard_desc: 'किसानों द्वारा, किसानों के लिए बनाई गई एआई-संचालित फसल रोग पहचान — जो सटीक कृषि को सभी के लिए सुलभ बनाती है।',
  get_in_touch: 'संपर्क करें',
  contact_desc: 'क्रॉपगार्ड के बारे में प्रश्न हैं? सहायता चाहिए या प्रतिक्रिया देना चाहते हैं? हमे आपसे सुनकर अत्यंत खुशी होगी।',
  we_respond_24_hours: 'हम 24 घंटे के भीतर जवाब देते हैं',
  our_contributors: 'हमारे योगदानकर्ता',
  meet_the_creators: 'फसल रोग विश्लेषण के पीछे के रचनाकारों से मिलें',
  support_center: 'सहायता केंद्र',
  help_faq: 'मदद और सामान्य प्रश्न',
  help_desc: 'क्रॉपगार्ड के एआई-संचालित सुविधाओं का अधिकतम लाभ उठाने के लिए आपको जो कुछ भी जानने की आवश्यकता है।',
  privacy_policy: 'गोपनीयता नीति',
  privacy_desc: 'हम आपकी गोपनीयता और आपके डेटा की सुरक्षा की रक्षा करने के लिए प्रतिबद्ध हैं।',
}

const mr: Record<string, string> = {
  ...en,
  dashboard: 'डॅशबोर्ड', predict: 'रोगाचा अंदाज', analytics: 'विश्लेषण', reports: 'अहवाल',
  farmers_guide: 'शेतकरी मार्गदर्शक', weather: 'हवामान', login: 'लॉगिन', register: 'नोंदणी', logout: 'लॉगआउट',
  upload_image: 'प्रतिमा अपलोड करा', disease_detected: 'रोग आढळला', confidence: 'आत्मविश्वास', treatment: 'उपचार', prevention: 'प्रतिबंध',
  my_dashboard: 'माझे डॅशबोर्ड', new_prediction: 'नवीन अंदाज', predict_disease: 'रोगाचा अंदाज', view_analytics: 'विश्लेषण पहा',
  upload_crop_image: 'पिकाची प्रतिमा अपलोड करा', track_trends: 'ट्रेंड ट्रॅक करा', weather_alert: 'हवामान अलर्ट', check_conditions: 'परिस्थिती तपासा',
  prevention_tips: 'प्रतिबंध टिप्स', stay_protected: 'संरक्षित रहा', weather_disease_risk: 'हवामान आणि रोग धोका',
  enter_region: 'प्रदेश प्रविष्ट करा (उदा. मुंबई)', get_weather: 'हवामान मिळवा', checking: 'तपासत आहे...', full_weather_page: 'पूर्ण हवामान पृष्ठ',
  total_predictions: 'एकूण अंदाज', avg_confidence: 'सरासरी आत्मविश्वास', unique_diseases: 'अद्वितीय रोग',
  prediction_history: 'अंदाज इतिहास', date: 'तारीख', disease: 'रोग', crop_type: 'पिक प्रकार',
  no_predictions_yet: 'अद्याप अंदाज नाही. प्रतिमा अपलोड करा!', risk: 'धोका',
  crop_disease_detection: 'पिक रोग शोध', upload_image_title: 'प्रतिमा अपलोड करा',
  drag_drop_or_click: 'प्रतिमा ड्रॅग करा किंवा निवडण्यासाठी क्लिक करा', drop_here: 'येथे ड्रॉप करा',
  crop_type_label: 'पिक प्रकार', region_label: 'प्रदेश', soil_type_label: 'माती प्रकार',
  select_crop_type: 'पिक प्रकार निवडा', select_soil_type: 'माती प्रकार निवडा', enter_region_placeholder: 'तुमचा प्रदेश प्रविष्ट करा',
  capture: 'कॅप्चर', cancel: 'रद्द', take_photo: 'फोटो घ्या', analyze: 'विश्लेषण', reset: 'रीसेट',
  please_select_image: 'कृपया प्रतिमा निवडा', prediction_completed: 'अंदाज पूर्ण!', prediction_failed: 'अंदाज अयशस्वी',
  camera_denied: 'कॅमेरा परवानगी द्या.',
  email: 'ईमेल', password: 'पासवर्ड', logging_in: 'लॉग इन होत आहे...', no_account_register: 'खाते नाही?',
  full_name: 'पूर्ण नाव', region_optional: 'प्रदेश (ऐच्छिक)', registering: 'नोंदणी होत आहे...', have_account_login: 'आधीच खाते आहे?',
  login_success: 'लॉगिन यशस्वी!', login_failed: 'लॉगिन अयशस्वी', register_success: 'नोंदणी यशस्वी!', register_failed: 'नोंदणी अयशस्वी',
  crop_filter: 'पिक फिल्टर', disease_frequency: 'रोग वारंवारता', crop_health: 'पिक आरोग्य',
  monthly_trends: 'मासिक ट्रेंड', region_wise: 'प्रदेशानुसार', export_pdf: 'PDF निर्यात', export_csv: 'CSV निर्यात',
  disease_map: 'रोग नकाशा', filter_by_crop: 'पिकानुसार फिल्टर', all_crops: 'सर्व', not_specified: 'निर्दिष्ट नाही',
  crop_disease_report: 'पिक रोग अहवाल', period: 'कालावधी', summary: 'सारांश',
  total_predictions_report: 'एकूण अंदाज', generate_report: 'अहवाल तयार करा', export_report: 'अहवाल निर्यात',
  farmers_guide_title: 'शेतकरी मार्गदर्शक', crop_care_tips: 'पिक काळजी टिप्स', seasonal_tasks: 'हंगामी कार्ये',
  spring: 'वसंत ऋतू', summer: 'उन्हाळा', fall: 'शरद ऋतू', winter: 'हिवाळा',
  weather_disease_risk_title: 'हवामान आणि रोग धोका', enter_region_weather: 'तुमचा प्रदेश प्रविष्ट करा',
  check_weather: 'हवामान तपासा', weather_conditions: 'हवामान परिस्थिती', temperature: 'तापमान', humidity: 'आर्द्रता',
  recommendation: 'शिफारस', high: 'उच्च', moderate: 'मध्यम', low: 'कमी',
  please_enter_region: 'कृपया प्रदेश प्रविष्ट करा', could_not_fetch_weather: 'हवामान मिळू शकले नाही.',
  welcome_back: 'परत स्वागत आहे',
  farm_overview: 'येथे आपल्या शेताचे विहंगावलोकन आहे',
  more: 'अधिक',
  about: 'बद्दल',
  contact: 'संपर्क',
  help: 'मदत',
  privacy: 'गोपनीयता',
  ai_disease_analysis: 'AI रोग विश्लेषण',
  upload_subtitle: 'त्वरित AI निदान आणि उपचारांच्या शिफारशींसाठी स्पष्ट पानाचा फोटो अपलोड करा.',
  image_ready: 'प्रतिमा तयार आहे — विश्लेषण क्लिक करा',
  image_format_hint: 'JPG, JPEG, PNG · जास्तीत जास्त 10MB',
  other_custom: 'इतर (कस्टम)',
  crop_placeholder: 'उदा. आंबा, केळी…',
  analysis_results: 'विश्लेषण परिणाम',
  analysis_failed: 'विश्लेषण अयशस्वी',
  try_again: 'पुन्हा प्रयत्न करा',
  suggested_diagnosis: 'सुचवलेले निदान · AI अंदाज',
  ai_confidence: 'AI आत्मविश्वास',
  low_confidence_warning: 'कमी आत्मविश्वास — प्रतिमेची गुणवत्ता किंवा प्रकाशयोजना अचूकतेवर परिणाम करू शकते.',
  est_crop_health: 'अंदाजित पीक आरोग्य',
  est_severity: 'अंदाजित तीव्रता',
  expert_review_recommended: 'तज्ज्ञांच्या पुनरावलोकनाची शिफारस केली आहे.',
  expert_review_details: 'हे दृश्यमान नमुन्यांवर आधारित AI-सुचवलेले परिणाम आहेत. पुष्टीकरणासाठी, कोणताही उपचार लागू करण्यापूर्वी स्थानिक कृषी विस्तार अधिकारी किंवा कृषी तज्ज्ञाचा सल्ला घ्या.',
  top_3_diseases: 'शीर्ष 3 संभाव्य आजार',
  top_3_desc: 'मॉडेलचा संभाव्यतेचा अंदाज — यापैकी कोणतीही वास्तविक स्थिती असू शकते.',
  likely: 'शक्यता',
  disease_analysis: 'रोग विश्लेषण',
  pathogen: 'रोगजनक',
  symptoms: 'लक्षणे',
  suggested_treatment: 'सुचवलेला उपचार (तज्ज्ञाशी पुष्टी करा)',
  treatment_warning: 'लागू करण्यापूर्वी नेहमी स्थानिक कृषी तज्ज्ञाकडून डोस आणि कीटकनाशकांच्या योग्यतेची पुष्टी करा.',
  soil_advice: 'माती आणि शेतीविषयक सल्ला',
  analyze_another: '↺ दुसऱ्या प्रतिमेचे विश्लेषण करा',
  no_results_yet: 'अद्याप कोणतेही परिणाम नाहीत',
  upload_instruction: 'सुरू करण्यासाठी पानाची प्रतिमा अपलोड करा आणि रोगाचे विश्लेषण करा वर क्लिक करा.',
  no_crop_health_data: 'पिकाच्या आरोग्याबाबत कोणताही डेटा उपलब्ध नाही. आकडेवारी पाहण्यासाठी पिकाच्या प्रकाराच्या माहितीसह अंदाज करा.',
  no_monthly_trend_data: 'कोणताही मासिक ट्रेंड डेटा उपलब्ध नाही. कालांतराने ट्रेंड पाहण्यासाठी अंदाज करा.',
  no_region_data: 'कोणताही प्रदेश डेटा उपलब्ध नाही. चार्ट पाहण्यासाठी प्रदेशाच्या माहितीसह अंदाज करा.',
  loading_reports: 'अहवाल लोड होत आहेत…',
  analytics_history: 'अॅनालिटिक्स आणि इतिहास',
  recent_predictions: 'अलीकडील रोगाचे अंदाज',
  actions: 'क्रिया',
  prediction_details: 'अंदाज तपशील',
  loading_details: 'तपशील लोड करत आहे…',
  live_weather_disease_risk: 'लाइव्ह हवामान · रोग धोका',
  real_time_weather_info: 'Open-Meteo कडील रिअल-टाइम डेटा — जगभरातील कोणत्याही शहरासाठी कार्य करते.',
  works_for_any_city: 'कोणत्याही शहर किंवा जिल्ह्यासाठी कार्य करते',
  enter_region_placeholder_2: 'उदा. पुणे, मुंबई, दिल्ली, बंगळुरू…',
  loading: 'लोड होत आहे…',
  based_on_current_conditions: 'सद्यस्थितीवर आधारित',
  risk_factors_detected: 'धोक्याचे घटक आढळले',
  weather_disclaimer: 'धोक्याची गणना लाइव्ह हवामान स्थितीवरून केली जाते. नेहमी शेतात जाऊन तपासणी करा — उपचारांचे निर्णय घेण्यापूर्वी स्थानिक कृषी तज्ज्ञाचा सल्ला घ्या.',
  precipitation: 'पर्जन्यमान',
  cloud_cover: 'ढगाळ वातावरण',
  dew_point: 'दव बिंदू',
  wind_speed: 'वाऱ्याचा वेग',
  high_disease_risk: 'उच्च रोग धोका',
  moderate_disease_risk: 'मध्यम रोग धोका',
  low_disease_risk: 'कमी रोग धोका',
  high_risk_advice: 'उच्च रोग धोका. ओव्हरहेड सिंचन टाळा, हवा वायुवीजन सुधारा आणि प्रतिबंधात्मक बुरशीनाशकाचा विचार करा. सुरुवातीच्या लक्षणांसाठी रोज पिकांची तपासणी करा.',
  moderate_risk_advice: 'मध्यम रोग धोका. पिकांवर लक्ष ठेवा, योग्य हवा खेळती राहण्याची खात्री करा आणि पानांवर जास्त आर्द्रता टाळा. दर २-३ दिवसांनी रोगाच्या चिन्हांची पाहणी करा.',
  low_risk_advice: 'कमी रोग धोका. उत्तम कृषी पद्धती सुरू ठेवा. सध्या पिकांच्या रोगजनकांसाठी परिस्थिती अनुकूल नाही.',
  please_enter_region_or_city: 'कृपया प्रदेश किंवा शहराचे नाव प्रविष्ट करा',
  finding_location: 'स्थान शोधत आहे…',
  loading_live_weather: 'थेट हवामान डेटा लोड करत आहे…',
  knowledge_hub: 'ज्ञान केंद्र',
  farmers_guide_subtitle: 'निरोगी पिकांसाठी तज्ञांच्या टिप्स, हंगामी मार्गदर्शक आणि उत्तम पद्धती.',
  quick_reference: 'द्रुत संदर्भ',
  tomato: 'टोमॅटो',
  potato: 'बटाटा',
  corn: 'मका',
  tomato_tip_1: 'मुळांजवळ पाणी द्या, पाने भिजवणे टाळा',
  tomato_tip_2: 'दररोज ६-८ तास सुर्यप्रकाश द्या',
  tomato_tip_3: 'आधारासाठी काठ्या किंवा पिंजरे वापरा',
  tomato_tip_4: 'दर २-३ आठवड्यांनी खत द्या',
  tomato_tip_5: 'किडींसाठी नियमित तपासणी करा',
  potato_tip_1: 'चांगला निचरा होणाऱ्या जमिनीत लावा',
  potato_tip_2: 'जमीन सतत ओलसर ठेवा',
  potato_tip_3: 'रोपे जसजशी वाढतील तसतशी त्यांच्याभोवती माती लावा',
  potato_tip_4: 'पाने पिवळी झाल्यावर कापणी करा',
  potato_tip_5: 'थंड, अंधाऱ्या जागी साठवा',
  corn_tip_1: 'चांगल्या परागीकरणासाठी ब्लॉक मध्ये लावा',
  corn_tip_2: 'आठवड्यातून एकदा खोलवर पाणी द्या',
  corn_tip_3: 'नायट्रोजनयुक्त खत द्या',
  corn_tip_4: 'दाणे दुधाळ झाल्यावर कापणी करा',
  corn_tip_5: 'पूर्ण उन्हात लावा',
  spring_task_1: 'जमीन तयार करा',
  spring_task_2: 'रोपे लावण्यास सुरुवात करा',
  spring_task_3: 'कंपोस्ट खत द्या',
  spring_task_4: 'सिंचन तपासा',
  summer_task_1: 'नियमित पाणी द्या',
  summer_task_2: 'रोपांभोवती आच्छादन करा',
  summer_task_3: 'किडींवर लक्ष ठेवा',
  summer_task_4: 'लवकर आलेल्या पिकांची कापणी करा',
  fall_task_1: 'शिल्लक पिकांची कापणी करा',
  fall_task_2: 'हिवाळ्यासाठी तयारी करा',
  fall_task_3: 'कव्हर पिके लावा',
  fall_task_4: 'अवजारे स्वच्छ करा',
  winter_task_1: 'पुढच्या हंगामाचे नियोजन करा',
  winter_task_2: 'उपकरणांची देखभाल करा',
  winter_task_3: 'बियाण्यांची ऑर्डर द्या',
  winter_task_4: 'मागील हंगामाचे पुनरावलोकन करा',
  watering_guide: 'पाणी देण्याचे मार्गदर्शक',
  watering_desc: 'सकाळी किंवा संध्याकाळी लवकर पाणी द्या. बहुतांश पिकांना प्रति आठवडा १-२ इंच पाण्याची गरज असते. पाणी देण्यापूर्वी जमिनीतील ओलावा तपासा.',
  sunlight_req: 'सूर्यप्रकाशाच्या गरजा',
  sunlight_desc: 'बहुतांश भाज्यांना ६-८ तास थेट सूर्यप्रकाशाची आवश्यकता असते. पालेभाज्या अंशतः सावली सहन करू शकतात.',
  disease_prev: 'रोग प्रतिबंध',
  disease_desc: 'दरवर्षी पिकांची फेरपालट करा, रोगप्रतिकारक वाण वापरा, योग्य अंतर ठेवा आणि प्रादुर्भाव झालेली रोपे ताबडतोब काढून टाका.',
  our_story: 'आमची कथा',
  about_cropguard: 'क्रॉपगार्ड बद्दल',
  about_cropguard_desc: 'शेतकऱ्यांनी, शेतकऱ्यांसाठी बनवलेली एआय-सक्षम पीक रोग ओळख — जी अचूक शेती सर्वांसाठी सुलभ करते.',
  get_in_touch: 'संपर्क साधा',
  contact_desc: 'क्रॉपगार्ड बद्दल प्रश्न आहेत? मदत हवी आहे किंवा प्रतिक्रिया द्यायची आहे? आम्हाला आपल्याकडून ऐकायला आवडेल.',
  we_respond_24_hours: 'आम्ही २४ तासांच्या आत प्रतिसाद देतो',
  our_contributors: 'आमचे योगदानकर्ते',
  meet_the_creators: 'पीक रोग विश्लेषणामागील निर्मात्यांना भेटा',
  support_center: 'मदत केंद्र',
  help_faq: 'मदत आणि वारंवार विचारले जाणारे प्रश्न',
  help_desc: 'क्रॉपगार्ड च्या एआय-सक्षम वैशिष्ट्यांचा जास्तीत जास्त फायदा घेण्यासाठी आपल्याला माहित असणे आवश्यक असलेली प्रत्येक गोष्ट.',
  privacy_policy: 'गोपनीयता धोरण',
  privacy_desc: 'आम्ही तुमची गोपनीयता आणि तुमच्या डेटाचे संरक्षण करण्यासाठी वचनबद्ध आहोत.',
}

const translations: Record<Language, Record<string, string>> = { en, hi, mr }

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>('en')

  useEffect(() => {
    const saved = localStorage.getItem('language') as Language
    if (saved && ['en', 'hi', 'mr'].includes(saved)) {
      setLanguageState(saved)
    }
  }, [])

  const setLanguage = (lang: Language) => {
    setLanguageState(lang)
    localStorage.setItem('language', lang)
  }

  const t = (key: string): string => {
    return translations[language]?.[key] ?? translations.en[key] ?? key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider')
  }
  return context
}
